NAME: megaphone
SRC: megaphone.cpp
FLAGS: -Wall -Wextra -Werror -std=c++98

make:
		c++ -Wall -Wextra -Werror -std=c++98 megaphone.cpp -o megaphone

re: clean make

clean: 
		rm -f megaphone
