NAME = BraiiiiiiinnnzzzZ
CC = c++
SRCS = main.cpp Zombie.cpp newZombie.cpp randomChump.cpp
CFLAGS = -Wall -Wextra -Werror -std=c++98

$(NAME):
	c++ $(CFLAGS) $(SRCS) -o $(NAME)

re: fclean $(NAME)

fclean: 
		rm -f BraiiiiiiinnnzzzZ

.PHONY: re fclean