NAME = BraiiiiiiinnnzzzZ
CC = c++
SRCS = main.cpp Zombie.cpp
CFLAGS = -Wall -Wextra -Werror -std=c++98

# $(NAME): 

all: 
	@$(CC) main.cpp Zombie.cpp $(CFLAGS) -o $(NAME)

re: clean all

clean: 
		rm -f BraiiiiiiinnnzzzZ


.PHONY: all re clean