NAME: crappy_phonebook
SRC: crappy_phonebook.cpp PhoneBook.cpp Contact.cpp
FLAGS: -Wall -Wextra -Werror -std=c++98

make:
		c++ -Wall -Wextra -Werror -std=c++98 crappy_phonebook.cpp PhoneBook.cpp Contact.cpp -o crappy_phonebook

re: clean make

clean: 
		rm -f crappy_phonebook